name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            chmod +x ./build_all.sh
            ./build_all.sh

      - name: Gather Artifacts
        run: |
          chmod +x ./gather_artifacts.sh
          ./gather_artifacts.sh

      - name: Install Hub
        run: |
          sudo apt-get update
          sudo apt-get install -y hub

      - name: Create Release and Upload Assets
        run: |
          set -x
          assets=()
          for asset in artifacts/*.pdf; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}