name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          scheme: full

      - name: Build LaTeX Documents
        run: |
          chmod +x ./build_all.sh
          ./build_all.sh

      - name: Gather Artifacts
        run: |
          chmod +x ./gather_artifacts.sh
          ./gather_artifacts.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pdf in artifacts/*.pdf; do
            echo "Uploading ${pdf}"
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: application/pdf" \
                 --data-binary @"${pdf}" \
                 "${{ steps.create_release.outputs.upload_url }}?name=$(basename "${pdf}")"
          done
